# ai/sign_definitions.py

SIGN_TO_TEXT = {
    "HELLO": "The person is greeting you.",
    "HOW_ARE_YOU": "The person is asking how you are.",
    "NICE_TO_MEET_YOU": "The person is expressing pleasure in meeting you.",
    "WHAT_IS_YOUR_NAME": "The person is asking your name.",
    "MY_NAME_IS": "The person is introducing their name.",
    "THANK_YOU": "The person is thanking you.",
    "YOU_ARE_WELCOME": "The person is responding politely.",
    "GOODBYE": "The person is saying goodbye.",
    "SEE_YOU_LATER": "The person is saying they will see you later.",
    "GOOD_MORNING": "The person is wishing you good morning.",
    "GOOD_NIGHT": "The person is wishing you good night.",
    "PLEASE": "The person is requesting politely.",
    "SORRY": "The person is apologizing.",
    "EXCUSE_ME": "The person is asking for attention politely.",
    "YES": "The person is agreeing.",
    "NO": "The person is disagreeing.",
    "STOP": "The person is asking to stop.",
    "WAIT": "The person is asking to wait.",
    "HELP_ME": "The person is asking for help.",
    "IM_HUNGRY": "The person is saying they are hungry.",
    "IM_THIRSTY": "The person is saying they are thirsty.",
    "IM_TIRED": "The person is saying they are tired.",
    "IM_BUSY": "The person is saying they are busy.",
    "IM_BORED": "The person is saying they are bored.",
    "EAT": "The person is referring to eating.",
    "WHAT": "The person is asking what.",
    "WHEN": "The person is asking when.",
    "FATHER": "The person is referring to their father.",
    "MOTHER": "The person is referring to their mother.",
    "FRIEND": "The person is referring to a friend."
}
